[package]
name = "fmtastic"
version = "0.1.0"
edition = "2021"
authors = ["Ruben Schmidmeister <ruben.schmidmeister@icloud.com>"]
license = "MIT/Apache-2.0"
readme = "readme.md"
repository = "https://github.com/bash/fmtastic"

[dependencies]
